// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :exec
INSERT INTO artifacts (
    id,
    slug,
    title,
    description,
    source_type,
    source_filename,
    sha256,
    size_bytes,
    project,
    repo_full_name,
    branch,
    commit_sha,
    dirty,
    agent,
    generator,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
`

type CreateArtifactParams struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	SourceType     SourceType         `json:"source_type"`
	SourceFilename string             `json:"source_filename"`
	Sha256         string             `json:"sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	Project        pgtype.Text        `json:"project"`
	RepoFullName   pgtype.Text        `json:"repo_full_name"`
	Branch         pgtype.Text        `json:"branch"`
	CommitSha      pgtype.Text        `json:"commit_sha"`
	Dirty          bool               `json:"dirty"`
	Agent          pgtype.Text        `json:"agent"`
	Generator      pgtype.Text        `json:"generator"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) error {
	_, err := q.db.Exec(ctx, createArtifact,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.SourceType,
		arg.SourceFilename,
		arg.Sha256,
		arg.SizeBytes,
		arg.Project,
		arg.RepoFullName,
		arg.Branch,
		arg.CommitSha,
		arg.Dirty,
		arg.Agent,
		arg.Generator,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getArtifactBySlug = `-- name: GetArtifactBySlug :one
SELECT id, slug, title, description, source_type, source_filename, sha256, size_bytes, project, repo_full_name, branch, commit_sha, dirty, agent, generator, created_at, updated_at
FROM artifacts
WHERE slug = $1
LIMIT 1
`

type GetArtifactBySlugParams struct {
	Slug string `json:"slug"`
}

func (q *Queries) GetArtifactBySlug(ctx context.Context, arg GetArtifactBySlugParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySlug, arg.Slug)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.SourceType,
		&i.SourceFilename,
		&i.Sha256,
		&i.SizeBytes,
		&i.Project,
		&i.RepoFullName,
		&i.Branch,
		&i.CommitSha,
		&i.Dirty,
		&i.Agent,
		&i.Generator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentArtifacts = `-- name: ListRecentArtifacts :many
SELECT id, slug, title, description, source_type, source_filename, sha256, size_bytes, project, repo_full_name, branch, commit_sha, dirty, agent, generator, created_at, updated_at
FROM artifacts
ORDER BY created_at DESC
LIMIT $1
`

type ListRecentArtifactsParams struct {
	Limit int32 `json:"limit"`
}

func (q *Queries) ListRecentArtifacts(ctx context.Context, arg ListRecentArtifactsParams) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listRecentArtifacts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.SourceType,
			&i.SourceFilename,
			&i.Sha256,
			&i.SizeBytes,
			&i.Project,
			&i.RepoFullName,
			&i.Branch,
			&i.CommitSha,
			&i.Dirty,
			&i.Agent,
			&i.Generator,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
