// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SourceType string

const (
	SourceTypeMarkdown SourceType = "markdown"
	SourceTypeHtml     SourceType = "html"
)

func (e *SourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceType(s)
	case string:
		*e = SourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceType: %T", src)
	}
	return nil
}

type NullSourceType struct {
	SourceType SourceType `json:"source_type"`
	Valid      bool       `json:"valid"` // Valid is true if SourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.SourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceType), nil
}

type Artifact struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Description    pgtype.Text        `json:"description"`
	SourceType     SourceType         `json:"source_type"`
	SourceFilename string             `json:"source_filename"`
	Sha256         string             `json:"sha256"`
	SizeBytes      int64              `json:"size_bytes"`
	Project        pgtype.Text        `json:"project"`
	RepoFullName   pgtype.Text        `json:"repo_full_name"`
	Branch         pgtype.Text        `json:"branch"`
	CommitSha      pgtype.Text        `json:"commit_sha"`
	Dirty          bool               `json:"dirty"`
	Agent          pgtype.Text        `json:"agent"`
	Generator      pgtype.Text        `json:"generator"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
