// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) error
	GetArtifactBySlug(ctx context.Context, arg GetArtifactBySlugParams) (Artifact, error)
	ListRecentArtifacts(ctx context.Context, arg ListRecentArtifactsParams) ([]Artifact, error)
}

var _ Querier = (*Queries)(nil)
