import MarkdownIt from "markdown-it"

import { type Artifact } from "../domain/Artifact.js"

const markdown = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true
})

export const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")

const pageShell = (title: string, body: string) =>
  `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, sans-serif; }
    body { margin: 0; background: Canvas; color: CanvasText; }
    main { max-width: 920px; margin: 0 auto; padding: 32px 20px 56px; }
    a { color: LinkText; }
    .artifact-card { border: 1px solid color-mix(in srgb, CanvasText 20%, transparent); border-radius: 12px; padding: 18px; margin: 16px 0; }
    .metadata { color: color-mix(in srgb, CanvasText 70%, transparent); font-size: 0.92rem; }
    .source-frame { width: 100%; min-height: 70vh; border: 1px solid color-mix(in srgb, CanvasText 20%, transparent); border-radius: 12px; background: white; }
    pre, code { white-space: pre-wrap; }
  </style>
</head>
<body>
${body}
</body>
</html>`

export const renderArtifactPage = (artifact: Artifact, source: string): string => {
  const rendered = artifact.sourceType === "markdown"
    ? `<article>${markdown.render(source)}</article>`
    : `<iframe class="source-frame" sandbox="allow-scripts allow-same-origin" srcdoc="${escapeHtml(source)}"></iframe>`

  return pageShell(
    artifact.title,
    `<main>
    <p><a href="/">← Recent artifacts</a></p>
    <h1>${escapeHtml(artifact.title)}</h1>
    <p class="metadata">Published ${escapeHtml(artifact.createdAt)} · ${
      escapeHtml(artifact.sourceType)
    } · <a href="/source/${escapeHtml(artifact.slug)}">Source</a></p>
    ${artifact.description === null ? "" : `<p>${escapeHtml(artifact.description)}</p>`}
    ${rendered}
  </main>`
  )
}

export const renderFeedPage = (artifacts: ReadonlyArray<Artifact>): string =>
  pageShell(
    "Agent Artifacts",
    `<main>
    <h1>Agent Artifacts</h1>
    <p class="metadata">Recent public artifacts generated by coding agents.</p>
    ${
      artifacts.length === 0 ?
        "<p>No artifacts published yet.</p>" :
        artifacts.map((artifact) =>
          `<section class="artifact-card">
      <h2><a href="/a/${escapeHtml(artifact.slug)}">${escapeHtml(artifact.title)}</a></h2>
      ${artifact.description === null ? "" : `<p>${escapeHtml(artifact.description)}</p>`}
      <p class="metadata">${escapeHtml(artifact.sourceType)} · ${escapeHtml(artifact.createdAt)} · <a href="/source/${
            escapeHtml(artifact.slug)
          }">Source</a></p>
    </section>`
        ).join("\n")
    }
  </main>`
  )
