import MarkdownIt from "markdown-it";

import { type Artifact } from "../domain/Artifact.js";

const markdown = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
});

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const pageShell = (title: string, body: string, options?: { readonly bodyClass?: string }) =>
  `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light dark; font-family: ui-sans-serif, system-ui, sans-serif; }
    body { margin: 0; background: Canvas; color: CanvasText; }
    main { max-width: 920px; margin: 0 auto; padding: 32px 20px 56px; }
    a { color: LinkText; }
    .artifact-card { border: 1px solid color-mix(in srgb, CanvasText 20%, transparent); border-radius: 12px; padding: 18px; margin: 16px 0; }
    .metadata { color: color-mix(in srgb, CanvasText 70%, transparent); font-size: 0.92rem; }
    .source-frame { width: 100%; min-height: 70vh; border: 1px solid color-mix(in srgb, CanvasText 20%, transparent); border-radius: 12px; background: white; }
    pre, code { white-space: pre-wrap; }
    .artifact-detail-page { height: 100vh; overflow: hidden; }
    .artifact-shell { height: 100vh; overflow: hidden; }
    .artifact-banner { height: 48px; box-sizing: border-box; display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 14px; padding: 0 16px; border-bottom: 1px solid color-mix(in srgb, CanvasText 16%, transparent); background: Canvas; }
    .artifact-back, .artifact-source-link { font-size: 0.875rem; white-space: nowrap; text-decoration: none; }
    .artifact-back:hover, .artifact-source-link:hover { text-decoration: underline; }
    .artifact-title { margin: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 1rem; font-weight: 600; }
    .artifact-preview { box-sizing: border-box; width: 100%; max-width: none; height: calc(100vh - 48px); margin: 0; padding: 0; overflow: auto; }
    .artifact-preview > article { box-sizing: border-box; width: 100%; min-height: 100%; padding: 24px; }
    .artifact-preview > .source-frame { display: block; width: 100%; height: 100%; min-height: 0; border: 0; border-radius: 0; }
  </style>
</head>
<body${options?.bodyClass === undefined ? "" : ` class="${escapeHtml(options.bodyClass)}"`}>
${body}
</body>
</html>`;

export const renderArtifactPage = (artifact: Artifact, source: string): string => {
  const rendered =
    artifact.sourceType === "markdown"
      ? `<article>${markdown.render(source)}</article>`
      : `<iframe class="source-frame" sandbox="allow-scripts allow-same-origin" srcdoc="${escapeHtml(source)}"></iframe>`;

  return pageShell(
    artifact.title,
    `<div class="artifact-shell">
    <header class="artifact-banner">
      <a class="artifact-back" href="/">← Recent artifacts</a>
      <h1 class="artifact-title">${escapeHtml(artifact.title)}</h1>
      <a class="artifact-source-link" href="/source/${escapeHtml(artifact.slug)}">Source</a>
    </header>
    <main class="artifact-preview">
      ${rendered}
    </main>
  </div>`,
    { bodyClass: "artifact-detail-page" },
  );
};

export const renderFeedPage = (artifacts: ReadonlyArray<Artifact>): string =>
  pageShell(
    "Agent Artifacts",
    `<main>
    <h1>Agent Artifacts</h1>
    <p class="metadata">Recent public artifacts generated by coding agents.</p>
    ${
      artifacts.length === 0
        ? "<p>No artifacts published yet.</p>"
        : artifacts
            .map(
              (artifact) =>
                `<section class="artifact-card">
      <h2><a href="/a/${escapeHtml(artifact.slug)}">${escapeHtml(artifact.title)}</a></h2>
      ${artifact.description === null ? "" : `<p>${escapeHtml(artifact.description)}</p>`}
      <p class="metadata">${escapeHtml(artifact.sourceType)} · ${escapeHtml(artifact.createdAt)} · <a href="/source/${escapeHtml(
        artifact.slug,
      )}">Source</a></p>
    </section>`,
            )
            .join("\n")
    }
  </main>`,
  );
